Feat/sprint13
InseeFrLab/lunatic-edt pull request #61
Opened 2023-11-08 17:32 UTC by lailabjil

2023-11-09 09:04 UTC, MichaelC67 requested changes

2023-11-09 09:04 UTC, MichaelC67 commented on src/ui/components/Planner/WeeklyPlanner/weeklyPlanner.spec.tsx
> +            { "dateJ1": todayStringValue },
Is it still useful with the new datastructure ?

2023-11-09 09:04 UTC, MichaelC67 commented on src/ui/components/Planner/WeeklyPlanner/weeklyPlanner.spec.tsx
> +        { "dateJ1_00H00": "true" },
Is it still useful with the new datastructure ?

2023-11-13 07:26 UTC, lailabjil commented on src/ui/components/CheckboxOneEdt/CheckboxOneEdt.tsx
> +        const isMobile1 = window.innerWidth <= 667;
To avoid having too many regressions and redoing the entire component, I relied on this variable to transform the data.

2023-11-13 09:30 UTC, lailabjil commented on src/ui/components/CheckboxOneEdt/CheckboxOneEdt.tsx
> +        response: { name: bindingDependencies[0] },
bindingDepenencies[0], bindingDepenencies[1], bindingDepenencies[2]  are the names of variables used, the constants selectedId, suggesterId and labelNewValue are the values of these variables

2023-11-13 09:59 UTC, MichaelC67 approved these changes

2023-11-13 09:59 UTC, merged